ajktown/api

src/domains/word/index.interface.ts, src/domains/word/word.domain.ts, src/dto/get-word-query.dto.ts, src/dto/post-word-body.dto.ts, src/dto/put-word-body.dto.ts, src/schemas/deprecated-word.schema.ts
When you study word, you want to know where you get the words. Wordnote now supports link for example sentence to make yourself remember your words even more.
- https://github.com/ajktown/docs/pull/21
- https://github.com/ajktown/api/pull/56
- https://github.com/ajktown/wordnote/pull/87
- At least one or more issue is linked to this PR
- [The issue template](https://github.com/ajktown/.github/blob/main/issue_template.md) has been replaced to the [issue](#issue) above, if no issue is related to this PR
=> Link for Example

src/domains/word/word.domain.ts
There is a bug that sometimes non-string is returned for `example` of `WordDomain`
- _None_
- At least one or more issue is linked to this PR
- [The issue template](https://github.com/ajktown/.github/blob/main/issue_template.md) has been replaced to the [issue](#issue) above, if no issue is related to this PR
=> Example undefined bug fix

src/domains/auth/access-token.domain.ts
Bug was introduced in the PR https://github.com/ajktown/api/pull/71 where old users without `createdAt` for UserEntityDoc  was not able to sign in.
=> UserEntity without createdAt bug with UserDomain

src/domains/word/index.interface.ts, src/domains/word/word.domain.ts
Now returns tags for shared word card as requested in https://github.com/ajktown/wordnote/issues/164#issuecomment-1913118287
=> Shared Word Card with Tags

src/domains/ritual/ritual-group.domain.ts, src/domains/ritual/ritual.domain.ts
The api returns action groups in the order of how its stored.
The order should be sorted in the way, that the oldest ending time always go to the last and
the earlier ones stay in the front.
=> Action group returns in time order

src/controllers/ritual.controller.ts, src/domains/action/action-group.domain.ts, src/domains/ritual/index.interface.ts, src/domains/ritual/ritual-group.domain.ts, src/domains/ritual/ritual.domain.ts, src/modules/ritual.module.ts, src/modules/user.module.ts, src/schemas/index.collections.ts, src/schemas/ritual.schema.ts, src/services/ritual.service.ts
CGT does not yet offer changing order of the action groups.
Ritual Domain will have its child action groups' order.
This PR first creates RitualSchema and related changes to do the following:
- Default Ritual created if not exist yet
- Ritual Schema introduced and actually saved in DB
- [x ] Final Operation Check is done
- [x  Every item on the checklist has been addressed accordingly
=> GET /rituals returns real ritual

src/controllers/ritual.controller.ts, src/domains/ritual/index.interface.ts, src/domains/ritual/parent-ritual.domain.ts, src/domains/ritual/ritual-group.domain.ts, src/domains/ritual/ritual.domain.ts, src/dto/patch-ritual-group-body.dto.ts, src/responses/get-ritual.res.ts, src/schemas/ritual.schema.ts, src/services/ritual.service.ts
We only support at most one ritual per account at this point.
The url only supports default one at this point
=> PUT ritual/default

src/domains/action/action-group.domain.ts
The current production API already runs this security fixes 
Anyone could post action for other users's action as long as they know `action-group`'s `id`
=> Fix security issue `POST /action-groups/:id/action`

src/domains/action/action-group.domain.ts, src/domains/action/action.domain.ts
Action Group Now Returns Level 1 for Late Commitment
=> Action Group Now Returns Level 1 for Late Commitment

src/controllers/action-group.controller.ts, src/domains/action/action-group.domain.ts, src/services/action-group.service.ts
This change allows users to delete their committed actions just in case if the following happens:
- Accidentally clicks `Done`
Deleting past commitments that is not today won't be provided, though even in the future.
=> Delete today's actions of action group

src/domains/action/action-group.domain.ts, src/services/word.service.ts
Fix variable name as it might confuse developers
=> Rename nullable atd

src/domains/preference/index.interface.ts, src/domains/preference/preference.domain.ts, src/schemas/preference.schema.ts
API wants to store user's recent tags when the following happens:
- new tags are posted for newly-created words
- new tags are posted for already-created words
To do the above, we first create the new props `recentTags` for preference.
=> Preference new props recentTags

src/domains/word/word.domain.ts, src/services/word.service.ts
API wants to store user's recent tags when the following happens:
- new tags are posted for newly-created words
- new tags are posted for already-created words
To do the above, we first create the new props `recentTags` for preference.
This was handled in https://github.com/ajktown/api/pull/110
Next, we would like to import preference model for modules that will eventually need these.
This was handled in https://github.com/ajktown/api/pull/111
Now, when user actually creates a word, it should update preference's recentTags
- Final Operation Check is …
=> Post word updates preference `recentTags`

src/domains/word/word.domain.ts, src/services/word.service.ts
https://github.com/ajktown/api/issues/113
=> Update word updates preference `recentTags`

src/domains/ritual/index.interface.ts, src/domains/ritual/parent-ritual.domain.ts, src/domains/ritual/ritual-group.domain.ts, src/domains/ritual/ritual.domain.ts, src/responses/get-ritual.res.ts, src/services/ritual.service.ts
Action group ids were missing some of the ids when using `PATCH /api/v1/rituals/default`
=> Fix bug where action group ids are not properly returned

src/domains/ritual/ritual.domain.ts, src/domains/word/word.domain.ts
dto can be undefined, and therefore should use if else like the following:
=> Fix where the api does not handle undefined `PutWordByIdBodyDTO`'s `tags`

src/constants/auth-mdl-excluded-paths.const.ts, src/controllers/user.controller.ts, src/domains/user/user.domain.ts, src/responses/get-user.res.ts
Returns basic information of a certain user, based on the given nickname (`mlajkim` for example):
```sh
imageUrl: string
firstName: string
middleName: string
lastName: string
nickname: string
bio: string
```
=> New API endpoint `/api/v1/users/mlajkim`

src/domains/preference/index.interface.ts, src/domains/preference/preference.domain.ts, src/dto/put-preference.dto.ts, src/schemas/preference.schema.ts
`PreferenceDocs` now contains `gptKeyApi` to utilize chat gpt
=> GPT Key Registable

src/domains/preference/index.interface.ts, src/domains/preference/preference.domain.ts, src/domains/word/index.interface.ts, src/domains/word/word.domain.ts, src/dto/get-word-query.dto.ts, src/dto/post-word-body.dto.ts, src/dto/put-preference.dto.ts, src/dto/put-word-body.dto.ts, src/schemas/deprecated-word.schema.ts, src/schemas/preference.schema.ts
Unlike the main `definition`, `subDefinition` contains sub meanings for WordDomain.
=> Support `subDefinition` props for `WordEntity`

src/domains/preference/index.interface.ts, src/domains/preference/preference.domain.ts, src/domains/word/index.interface.ts, src/domains/word/word.domain.ts, src/dto/get-word-query.dto.ts, src/dto/post-word-body.dto.ts, src/dto/put-preference.dto.ts, src/dto/put-word-body.dto.ts, src/middleware/auth.middleware.ts, src/schemas/deprecated-word.schema.ts, src/schemas/preference.schema.ts
Apply `UnauthorizedException` => `UnidentifiedUserError` instead
=> Apply `UnauthorizedException` => `UnidentifiedUserError` instead

src/controllers/action-group.controller.ts, src/domains/action/action-group.domain.ts, src/domains/action/action.domain.ts, src/domains/action/index.interface.ts, src/dto/post-action.dto.ts, src/schemas/action.schema.ts, src/services/action-group.service.ts
`POST /api/v1/action-groups/{id}` now supports a new dto attribute `isDummy` with the following behavior:
- `undefined`: the action posted under the action group with given {id} is a valid action committed
- `false`: the action posted under the action group with given {id} is a valid action committed
- `true`: the action posted under the action group with given {id} is not valid and cannot/won't be committed for the day.
=> API accepts dummy attribute for not performed action

src/domains/action/action-group.domain.ts, src/responses/get-action-groups.res.ts
API now returns  `derivedState` with the following attribute:
```
{
isOnTimeCommittable: this.isOnTimeCommittable,
isDummyCommittable: this.isDummyCommittable,
isLateCommittable: this.isLateCommittable,
isDeletable: this.isDeletable,
}
```
FEs can use `derivedState` to determine UIs, rather than calculating their own.
=> Derived state

package.json, src/domains/action/action-group.domain.ts, src/domains/ritual/ritual.domain.ts, yarn.lock
NestJS fails to support eslint 9, and AJK Town has decided to downgrade the eslint package from 9.0.0 => 8.57.0.
=> Fix yarn inspect not working by downgrading eslint

src/domains/action/action-group.domain.ts, src/domains/action/action.domain.ts
Bug was found in the derived state
=> Fix derived state bug

src/controllers/ritual.controller.ts, src/domains/ritual/parent-ritual.domain.ts, src/dto/patch-ritual-group-body.dto.ts
Endpoint `GET /api/v1/rituals/` already support a key `isArchived` in a body.
The `PATCH /api/v1/rituals/default` should do the same
=> New body `isArchived` for `PATCH /api/v1/rituals/default`

src/domains/action/action-group.domain.ts, src/domains/action/index.interface.ts, src/handlers/time.handler.ts
Returns the `firstYear` in `api/v1/action-groups/:id` as the following:
```
{
"props": {
...
"firstYear": 2024,
},
...
}
```
=> feat: `api/v1/action-groups/:id` returns `firstYear`

src/controllers/ritual.controller.ts, src/services/ritual.service.ts
`PATCH /api/v1/rituals/default` now return the same format as the `GET /api/v1/rituals`
=> refactor: for reusability

src/controllers/user.controller.ts, src/domains/auth/oauth-payload.domain.ts, src/domains/ritual/ritual-group.domain.ts, src/domains/user/index.interface.ts, src/domains/user/user.domain.ts, src/dto/patch-user.dto.ts, src/errors/500/critical.error.ts, src/schemas/deprecated-user.schema.ts, src/services/user.service.ts
Want to provider ways to have `nickname`, so I would like to offer an endpoint to change the nickname.
successful nickname change (i.e `my-nickname`):
if setting nickname is already set by yours:
If nickname already exists:
Returns the following if body is empty:
=> Feat: `PATCH /api/users` with `{ nickname: string }`

src/domains/action/action-group.domain.ts, src/responses/get-action-groups.res.ts
We want to keep motivating users not to lose their streak (falling off the wagon) by showing each action group's streak.
Humans often get motivated by not losing what they have, more than getting what they do not have.
`GetActionGroupRes` now has a new derived field `streak`.
If user does multiple times, the streak goes up.
- N/A
- Review Code
- Check if …
=> feat: `GetActionGroupRes` now has a new derived field `streak`

src/factories/get-word-query.factory.ts
We want to include `subDefinition` of domain `WordDomain` as search result following:
Implemented as the screenshot above
- N/A
- Review Code
- Check if there are any other missing TODOs (Checklists) that are not yet listed
- Check if issue under `Development` is fully handled if exists
=> Feat: Search Input now includes `subDefinition` of your word

src/domains/word/index.interface.ts, src/domains/word/word-chunk.domain.ts, src/domains/word/word.domain.ts, src/dto/get-word-query.dto.ts, src/dto/patch-word-body.dto.ts, src/factories/get-word-query.factory.ts, src/schemas/deprecated-word.schema.ts
Sometimes, users find themselves wanting to focus on memorizing certain terms they learned years ago. However, even if they favorite a word, it gets pushed down over time since the favorite list sorts words by the earliest added.
It would be great to have a pin feature, allowing users to keep specific words at the top of their list at all times. This way, users can prioritize key terms while still using both the favorite and pin features based on their needs.
Created a new field `isPinned` for `Word` Schema
- N/A
- `What's done` …
=> Feat: New field `isPinned` for `Word` Schema
