src/dto/index.root.ts
src/factories/get-word-query.factory.ts
src/factories/index.root.ts
src/services/word.service.ts

API: https://github.com/ajktown/api/pull/7
FE: https://github.com/ajktown/wordnote/pull/25

Get words with search input

---

src/controllers/auth.controller.ts
src/lambdas/get-env.lambda.ts
src/lambdas/get-res-with-removed-http-cookie.lambda.ts
src/main.module.ts
src/middleware/auth.middleware.ts
src/responses/get-who-am-i.res.ts
src/services/auth.service.ts

Doc: https://github.com/ajktown/docs/pull/8
FE: https://github.com/ajktown/wordnote/pull/29
API: https://github.com/ajktown/api/pull/11

Sign out Feature

---

src/controllers/word.controller.ts
src/domains/semester/semester-details.domain.ts
src/domains/semester/semester.domain.ts
src/domains/word/word-chunk.domain.ts
src/dto/get-word-query.dto.ts
src/handlers/get-pagination.handler.ts
src/responses/get-words.res.ts
src/services/semester.service.ts

FE: https://github.com/ajktown/wordnote/pull/32
API: https://github.com/ajktown/api/pull/14

All Semester Tag Removed

---

src/domains/auth/access-token.domain.ts
src/domains/user/user.domain.ts
src/domains/word/word-chunk.domain.ts
src/responses/get-who-am-i.res.ts
src/services/auth.service.ts
src/services/semester.service.ts
src/services/word.service.ts

FE: https://github.com/ajktown/wordnote/pull/33
API: https://github.com/ajktown/api/pull/15

Profile Picture

---

src/controllers/word.controller.ts
src/domains/word/word.domain.ts
src/dto/put-word-bofy.dto.ts
src/services/word.service.ts

FE: https://github.com/ajktown/wordnote/pull/35
API: https://github.com/ajktown/api/pull/17

Put Word Feature

---

src/domains/word/word-chunk.domain.ts
src/lambdas/get-jwt-options.lambda.ts
src/middleware/auth.middleware.ts
src/responses/get-words.res.ts

FE: https://github.com/ajktown/wordnote/pull/38
API: https://github.com/ajktown/api/pull/20

No longer gets individual ids

---

src/domains/index.root.ts
src/domains/word/word.domain.ts

Issue: https://github.com/ajktown/api/issues/30

Tags Should Be Unique By Api

---

src/domains/word/word-chunk.domain.ts

We have spotted the logical bug of the automatic semester deletion

Automatic Delete Semester Logical Bug Fixed

---

src/controllers/word.controller.ts
src/modules/word.module.ts
src/responses/post-word.res.ts

Issue: https://github.com/ajktown/wordnote/issues/47
FE: https://github.com/ajktown/wordnote/pull/48
API: https://github.com/ajktown/api/pull/39

Returns Semester for post word

---

README.md

Docker hub public image

---

src/domains/auth/access-token.domain.ts
src/interceptors/logging.interceptor.ts
src/main.module.ts

Logger for every api call

---

.vscode/settings.json
README.md
k8s/deployment.yaml
src/constants/auth-mdl-excluded-paths.const.ts
src/controllers/app.controller.ts
src/interceptors/logging.interceptor.ts
src/main.module.ts
src/main.ts
src/middleware/auth.middleware.ts
src/modules/auth.module.ts
src/services/app.service.ts
src/services/auth.service.ts

Current API Server lacks logging

Logger for google sign in error

---

README.md

_None_
Also wanted to automate `kubectl apply -f k8s`

Very simple doc modified

---

README.md
src/domains/semester/semester-details.domain.ts
src/domains/word/word.domain.ts
src/factories/index.root.ts
src/handlers/time.handler.spec.ts
src/handlers/time.handler.ts

The current problem is that sometimes it shows daysAgo, but the data is not actually present

fix: timezone for handler

---

.vscode/settings.json
src/domains/semester/semester.domain.ts
src/domains/word/index.interface.ts
src/domains/word/word.domain.ts
src/dto/get-word-query.dto.ts
src/dto/post-word-body.dto.ts
src/dto/put-word-body.dto.ts
src/factories/get-word-query.factory.ts
src/factories/index.root.ts
src/responses/get-words.res.ts
src/responses/post-word.res.ts
src/schemas/deprecated-word.schema.ts
src/services/word.service.ts

- https://github.com/ajktown/docs/pull/25
- https://github.com/ajktown/wordnote/issues/105
- https://github.com/ajktown/api/pull/63

Archive feature for words

---

src/controllers/auth.controller.ts
src/domains/semester/semester.domain.ts
src/services/auth.service.ts

Get Auth API with Automatic Ajktown Access Token Refresh

---

src/controllers/app.controller.spec.ts
src/services/app.service.ts

The current `https://api.ajktown.com` returns `Hello World from AJK Town API Service!`
It will be great if it returns `https://wordnote.ajktown.com` too for advertisement purpose.
- _None_
- You can directly copy background with issue from the samed/different repository.

Checkout Wordnote from AJK Town Helloworld

---

src/domains/auth/access-token.domain.ts
src/domains/user/user.domain.ts

https://github.com/ajktown/wordnote/issues/128
- _None_
- You can directly copy background with issue from the samed/different repository.

Returns isFirstTime for "First Time User with Confetti"

---

README.md

I've found a typo
- You can directly copy background with issue from the samed/different repository.

Readme Fix Typo

---

.env.sample
src/lambdas/get-env.lambda.ts

CORS cannot have multiple cors at this point
- Handles 0 CORS
- Handles 1 CORS
- Handles 2+ CORS
Please copy and paste the following into your review, ensuring each checkbox is marked as checked
```
```

Handles Multiple CORS

---

k8s/deployment.yaml
src/constants/action-group.const.ts
src/controllers/action-group.controller.ts
src/domains/action/action-group.domain.ts
src/domains/action/action.domain.ts
src/domains/action/index.interface.ts
src/domains/word/word.domain.ts
src/dto/get-word-query.dto.ts
src/dto/post-action.dto.ts
src/factories/get-word-query.factory.ts
src/factories/index.root.ts
src/handlers/time.handler.ts
src/lambdas/get-env.lambda.ts
src/main.module.ts
src/modules/action-group.module.ts
src/schemas/action.schema.ts
src/schemas/index.collections.ts
src/services/action-group.service.ts

Return ActionsGroupDomain for Daily Post One Word Card challenge
Please copy and paste the following into your review, ensuring each checkbox is marked as checked
```
```

Returns Action Group For Post Word Consistency

---

.github/ISSUE_TEMPLATE/bug.yaml
.github/ISSUE_TEMPLATE/dependency.yaml
.github/ISSUE_TEMPLATE/documentation.yaml
.github/ISSUE_TEMPLATE/enhancement.yaml
.github/ISSUE_TEMPLATE/infrastructure.yaml
.github/ISSUE_TEMPLATE/performance.yaml
.github/ISSUE_TEMPLATE/refactor.yaml

https://github.com/ajktown/api/issues/74

Kubernetes like issue for this repository

---

src/factories/get-word-query.factory.ts

The search function provided does not cover pronunciation and meaning for search.

Include Pronunciation and Meaning for Search

---

.vscode/settings.json
src/constants/auth-mdl-excluded-paths.const.ts
src/controllers/user.controller.ts
src/domains/ritual/ritual-group.domain.ts
src/domains/ritual/ritual.domain.ts
src/domains/user/user.domain.ts
src/errors/400/more-than-one-user-with-same-email-address.error.ts
src/main.module.ts
src/modules/user.module.ts
src/services/ritual.service.ts
src/services/user.service.ts

AJK Town is preparing to launch public rituals of any user.
The first step of the launch is to launch admin of AJK Town or myself with nickname `mlajkim`.
- Implement `GET /users/mlajkim/action-groups/:id`that returns mlajkim's action without any credential required

GET /users/mlajkim/rituals

---

README.md

https://github.com/ajktown/api/issues/92

Buy me coffee in README.md

---

README.md
src/domains/ritual/ritual.domain.ts

https://github.com/ajktown/api/issues/96

Introduce dev_api for developers of API 

---

src/controllers/user.controller.ts
src/responses/get-users.res.ts
src/services/user.service.ts

`/api/v1/users` return the number of users of AJK Town, and the joined date (createdDate) of the 5 latest ones

Implement api path `/api/v1/users`

---

src/domains/user/user.domain.ts
src/responses/get-user.res.ts

Display name

---

src/domains/action/action-group.domain.ts

Dummy Level 0

---

src/controllers/preference.controller.ts
src/controllers/word.controller.ts

https://github.com/ajktown/api/issues/131

Deprecate PUT endpoints

---

src/controllers/action-group.controller.ts
src/controllers/ritual.controller.ts
src/domains/archive/archive.domain.ts
src/domains/archive/index.interface.ts
src/domains/ritual/index.interface.ts
src/domains/ritual/parent-ritual.domain.ts
src/domains/ritual/ritual-group.domain.ts
src/domains/ritual/ritual.domain.ts
src/dto/get-rituals-query.dto.ts
src/dto/index.validator.ts
src/dto/patch-ritual-group-body.dto.ts
src/dto/post-archived-action-group.dto.ts
src/modules/action-group.module.ts
src/modules/ritual.module.ts
src/modules/user.module.ts
src/schemas/archive.schema.ts
src/schemas/index.collections.ts
src/services/action-group.service.ts
src/services/ritual.service.ts

Archive action group with given `id`

Archive action group `POST /api/v1/action-groups/{id}/archive`

---

.github/workflows/docker-image.yaml

The current github pipeline builds an image on non-arm CPU, and the current ajktown's production ec2 instance uses arm CPU.

Pipeline latest removed

---

k8s/deployment.yaml
src/lambdas/get-env.lambda.ts

New CORS golf.ajktown.com

---

src/controllers/shared-resource.controller.ts
src/services/action-group.service.ts
src/services/ritual.service.ts
src/services/semester.service.ts
src/services/shared-resource.service.ts
src/services/user.service.ts
src/services/word.service.ts

refactor: `private readonly` for non-assigned methods/props for class

---

.github/workflows/docker-image.yaml
src/domains/ritual/parent-ritual.domain.spec.ts
src/domains/ritual/parent-ritual.domain.ts
src/handlers/time.handler.spec.ts
src/schemas/action-group.schema.sample.ts
src/schemas/archive.schema.sample.ts
src/schemas/deprecated-user.schema.sample.ts
src/schemas/index.md
src/schemas/ritual.schema.sample.ts

The bug was found where the order is not correct:
https://github.com/ajktown/ConsistencyGPT/issues/67
We at first believed that the bug was fixed in PR: https://github.com/ajktown/ConsistencyGPT/pull/76
But it still does not work.
- Fix the bug found in the API side
- Implement a unit test 
- https://github.com/ajktown/ConsistencyGPT/pull/76
- Review Code …

Bugfix: Action Group Order

---

src/controllers/action-group.controller.ts
src/domains/action/action-group.domain.ts
src/errors/400/data-not-selectable.error.ts
src/handlers/time.handler.ts
src/responses/get-action-groups.res.ts
src/services/action-group.service.ts

https://github.com/ajktown/ConsistencyGPT/issues/85
Implement a new endpoint `DELETE /api/v1/action-groups/{id}/yesterday`
- N/A
- Review Code
- Check if there are any other missing TODOs (Checklists) that are not yet listed
- Check if issue under `Development` is fully handled if exists

Feat: new endpoint `DELETE /api/v1/action-groups/{id}/yesterday`

---

src/domains/auth/access-token.domain.ts

Refactor is required as I've found a unnecessary variable that is used only once.
Fix the Issue defined above in `Background`
- N/A
- Review Code
- Check if there are any other missing TODOs (Checklists) that are not yet listed
- Check if issue under `Development` is fully handled if exists

Refactor: AccessTokenDomain

---

src/domains/ritual/index.interface.ts
src/domains/ritual/ritual.domain.ts
src/domains/ritual_action_group/index.interface.ts
src/domains/ritual_action_group/ritual-action-group-group.domain.ts
src/domains/ritual_action_group/ritual-action-group.domain.spec.ts
src/domains/ritual_action_group/ritual-action-group.domain.ts
src/responses/get-ritual.res.ts
src/services/ritual.service.ts

The same as "Background" in https://github.com/ajktown/api/issues/163
Here: https://github.com/ajktown/docs/pull/117
None
None
- `What's done?` is filled
- `What are the related PRs?` is filled
- `What's next?` is filled
- Mobile View Operation Check is done, if frontend related
- Double-check `What's done?` matches to the actual changes
- Review Code
- Check if there are any other missing TODOs (Checklists) that are not yet listed
- Check if issue …

Refactor: rebrand each domain under `src/domains/ritual`

---

src/domains/preference/index.interface.ts
src/domains/preference/preference.domain.ts
src/dto/patch-preference.dto.ts
src/schemas/preference.schema.ts

https://github.com/ajktown/ConsistencyGPT/issues/99
Implement new user preference
None
- CGT will have a new PR using this API change
- `What's done?` is filled
- `What are the related PRs?` is filled
- `What's next?` is filled
- Mobile View Operation Check is done, if frontend related
- Double-check `What's done?` matches to the actual changes
- Appropriate ajktown/docs sync pr done if needed
- Review Code
- Check if there are any other missing …

Feat: `PATCH /api/v1/preference` with `useProgressDialog`
